print("30" + " " + "Days" + " " + "Of" + " " + "Python")
print('Coding' + ' ' + 'For' + ' ' + 'All')
company = "Coding For All"
print(company)
print(len(company))
print(company.upper())
print(company.lower())
print(company.capitalize())
print(company.title())
print(company.swapcase())
print(company[1 :3])
print(company.index("C"))
print(company.index("F"))
print(company.replace("Coding", "Python"))
print(company.replace("All", "Everyone"))
print(company.split())
string = "Python for Everyone"
print(string.split(" "))
print("Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon".split(", "))
print(company[0])
print(company[-1])
print(company[10])